language: node_js
node_js:
  - '8.9'

cache:
  directories:
    - node_modules
    - tools

before_install:
  - npm install
  - cd ./tools
  - wget -nc http://gosspublic.alicdn.com/ossutil/1.6.12/ossutil64
  - chmod 755 ossutil64
  - ./ossutil64 config -e "${OSS_ENDPOINT}" -i "${OSS_AKI}" -k "${OSS_AKS}"
  - cd ..

script:
  - npm run pdf

after_success:
  - cd ./dist
  - zip -r blog.zip ./*
  ## 删除OSS上旧文件
  - ../tools/ossutil64 rm oss://wzb-resume/ -r -f
  ## 上传zip文件
  - ../tools/ossutil64 cp -f blog.zip oss://wzb-resume/
